### ISSUE TITLE
Feature Suggestion - Move Selected Tabs to Last Active Window (Multiple Tabs)

### ISSUE THREAD

**Issue by Cr8zyIvan** [MorganTwoZero/move-tab#2]
I'm assuming this is the repository for the Firefox Extension "Move tab to the last window".

I love the Extension. Light Weight, works, and it does exactly what it's supposed to do. I would love to be able to Move Multiple Tabs (the Selected Tabs) in the Active Window, to the Last active Window.

Thanks, Cheers!

**Comment by MorganTwoZero** [comment]
Hello! I believe you've asked about this [#1](https://github.com/MorganTwoZero/move-tab/issues/1). Nothing has changed since then. The best I can help you with is to suggest that you look for an extension that's better suited for this task.

**Comment by Cr8zyIvan** [comment]
Oh geeze... I'm so sorry. Will do.
